export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_AUTHENTICATED_REQUEST_FAIL =
  'USER_AUTHENTICATED_REQUEST_FAIL';
export const USER_UNAUTHENTICATED = 'USER_UNAUTHENTICATED';
export const USER_AUTHENTICATED_REQUEST = 'USER_AUTHENTICATED_REQUEST';
